//
//  CharmKind+Names.swift
//  Hangly
//
//  What each charm is called.
//

import Foundation

/// Held apart from the declaration so that the list of charms stays something
/// you can read, and from the symbols for length alone.
extension CharmKind {
    /// Must match the `name` in `CharmLibrary.json`; a test enforces it.
    var displayName: String {
        switch self {
        case .circle: "Bead"
        case .camera: "Camera"
        case .star: "Star"
        case .heart: "Heart"
        case .diamond: "Diamond"
        case .nazar: "Nazar boncuğu"
        case .hamsa: "Hamsa"
        case .nimbuMirchi: "Nimbu-mirchi"
        case .ghanta: "Ghanta"
        case .drishtiBommai: "Drishti bommai"
        case .panchangJie: "Pánchángjié"
        case .daruma: "Daruma"
        case .manekiNeko: "Maneki-neko"
        case .horseshoe: "Horseshoe"
        case .scarab: "Scarab"
        case .himmeli: "Himmeli"
        case .dreamCatcher: "Dream Catcher"
        case .spiderMan: "Spider-Man"
        case .captainAmericaShield: "Captain America Shield"
        case .ironManHelmet: "Iron Man Helmet"
        case .thorHammer: "Thor Hammer"
        case .hulkFist: "Hulk Fist"
        case .spiderManSwinging: "Spider-Man Swinging"
        case .batmanSymbol: "Batman Symbol"
        case .supermanShield: "Superman Shield"
        case .wonderWomanEmblem: "Wonder Woman Emblem"
        case .shazamLightning: "Shazam Lightning"
        case .greenLanternRing: "Green Lantern Ring"
        case .vel: "Vel"
        case .vinayagarCoin: "Vinayagar Coin"
        case .omSymbol: "OM Symbol"
        case .karuppuStatue: "Karuppu Statue"
        case .templeBell: "Temple Bell"
        case .btsMemberOne: "RM"
        case .btsMemberTwo: "Jin"
        case .btsMemberThree: "SUGA"
        case .btsMemberFour: "j-hope"
        case .btsMemberFive: "Jimin"
        case .btsMemberSix: "V"
        case .btsMemberSeven: "Jungkook"
        case .ronaldoJersey: "Ronaldo 7"
        case .messiJersey: "Messi 10"
        case .neymarJersey: "Neymar 10"
        case .realMadridCrest: "Real Madrid"
        case .fcBarcelonaCrest: "FC Barcelona"
        case .billieEilish: "Billie Eilish"
        case .xxxtentacion: "XXXTentacion"
        case .michaelJackson: "Michael Jackson"
        case .taylorSwift: "Taylor Swift"
        case .juiceWrld: "Juice WRLD"
        case .theWeeknd: "The Weeknd"
        case .rachelGreen: "Rachel Green"
        case .monicaGeller: "Monica Geller"
        case .rossGeller: "Ross Geller"
        case .joeyTribbiani: "Joey Tribbiani"
        case .chandlerBing: "Chandler Bing"
        case .phoebeBuffay: "Phoebe Buffay"
        case .walterWhite: "Walter White"
        case .jessePinkman: "Jesse Pinkman"
        case .saulGoodman: "Saul Goodman"
        case .gusFring: "Gus Fring"
        case .mikeEhrmantraut: "Mike Ehrmantraut"
        case .heisenberg: "Heisenberg"
        case .rv: "RV"
        case .eleven: "Eleven"
        case .mikeWheeler: "Mike Wheeler"
        case .dustinHenderson: "Dustin Henderson"
        case .lucasSinclair: "Lucas Sinclair"
        case .willByers: "Will Byers"
        case .demogorgon: "Demogorgon"
        case .spiderManGwen: "Spider-Man and Gwen"
        case .eyeOfAgamotto: "Eye of Agamotto"
        case .stormbreaker: "Stormbreaker"
        case .doctorDoom: "Doctor Doom"
        case .deadpoolWolverine: "Deadpool and Wolverine"
        case .maxMayfield: "Max Mayfield"
        case .steveHarrington: "Steve Harrington"
        case .ronaldoPortugal: "Ronaldo Portugal"
        case .ronaldoBicycleKick: "Ronaldo Bicycle Kick"
        case .ballonDor: "Ballon d'Or"
        case .championsLeagueTrophy: "Champions League Trophy"
        case .rudraksha: "Rudraksha"
        case .shivaLingam: "Shiva Lingam"
        case .buddha: "Buddha"
        case .hanuman: "Hanuman"
        case .kaaba: "Kaaba"
        case .greenDome: "Green Dome"
        case .crescentAndStar: "Crescent and Star"
        case .allahPendant: "Allah Pendant"
        case .cross: "Cross"
        case .dove: "Dove of Peace"
        case .prayingAngel: "Praying Angel"
        case .sacredHeart: "Sacred Heart"
        case .luffy: "Monkey D. Luffy"
        case .zoro: "Roronoa Zoro"
        case .nami: "Nami"
        case .usopp: "Usopp"
        case .sanji: "Sanji"
        case .chopper: "Tony Tony Chopper"
        case .robin: "Nico Robin"
        case .ace: "Portgas D. Ace"
        case .harryPotter: "Harry Potter"
        case .hermioneGranger: "Hermione Granger"
        case .ronWeasley: "Ron Weasley"
        case .albusDumbledore: "Albus Dumbledore"
        case .lordVoldemort: "Lord Voldemort"
        case .hedwig: "Hedwig"
        case .goldenSnitch: "Golden Snitch"
        case .deathlyHallows: "Deathly Hallows"
        case .benTennyson: "Ben Tennyson"
        case .fourArms: "Four Arms"
        case .heatblast: "Heatblast"
        case .xlr8: "XLR8"
        case .diamondhead: "Diamondhead"
        case .cannonbolt: "Cannonbolt"
        case .upgrade: "Upgrade"
        case .wildmutt: "Wildmutt"
        case .omnitrix: "Omnitrix"
        case .erenYeager: "Eren Yeager"
        case .mikasaAckerman: "Mikasa Ackerman"
        case .leviAckerman: "Levi Ackerman"
        case .arminArlert: "Armin Arlert"
        case .colossalTitan: "Colossal Titan"
        case .attackTitan: "Attack Titan"
        case .surveyCorpsEmblem: "Survey Corps Emblem"
        case .cadetCorpsEmblem: "Cadet Corps Emblem"
        case .narutoUzumaki: "Naruto Uzumaki"
        case .sasukeUchiha: "Sasuke Uchiha"
        case .kakashiHatake: "Kakashi Hatake"
        case .itachiUchiha: "Itachi Uchiha"
        case .minatoNamikaze: "Minato Namikaze"
        case .kurama: "Kurama"
        case .akatsukiCloud: "Akatsuki Cloud"
        case .sharingan: "Mangekyō Sharingan"
        case .jonSnow: "Jon Snow"
        case .daenerysTargaryen: "Daenerys Targaryen"
        case .tyrionLannister: "Tyrion Lannister"
        case .nightKing: "Night King"
        case .houseStark: "House Stark"
        case .houseTargaryen: "House Targaryen"
        case .houseLannister: "House Lannister"
        case .ironThrone: "Iron Throne"
        case .airJordan1Chicago: "Air Jordan 1 Chicago"
        case .airJordan1Bred: "Air Jordan 1 Bred Patent"
        case .airJordan4FireRed: "Air Jordan 4 Fire Red"
        case .airJordan11Concord: "Air Jordan 11 Concord"
        case .airJordan3: "Air Jordan 3"
        case .airJordan6Carmine: "Air Jordan 6 Carmine"
        case .airJordan5: "Air Jordan 5"
        case .offWhiteJordan1: "Off-White Air Jordan 1"
        case .pikachu: "Pikachu"
        case .charmander: "Charmander"
        case .squirtle: "Squirtle"
        case .bulbasaur: "Bulbasaur"
        case .charizard: "Charizard"
        case .dragonair: "Dragonair"
        case .mewtwo: "Mewtwo"
        case .umbreon: "Umbreon"
        case .ashAndPikachu: "Ash and Pikachu"
        case .pokeBall: "Poké Ball"
        }
    }
}
