//
//  CharmCatalog.Generated.cs
//  Hangly
//
//  GENERATED FILE — DO NOT EDIT.
//
//  Written by tools/generate-catalogue.py from reference/swift/. Eighty-one
//  entries of pure data, read out of the Swift rather than typed again, because
//  a mistyped mass is a bug no compiler sees and only a screenshot catches.
//
//  To change a charm, change the Swift and re-run the generator.
//

namespace Hangly.Core.Models;

public static partial class CharmCatalog
{
    /// <summary>Every built-in charm, in the order the charm menu offers them.</summary>
    public static IReadOnlyList<CharmCatalogEntry> All { get; } =
    [
        new(
            Id: "nazar",
            DisplayName: "Nazar boncuğu",
            FileName: "Nazar Boncuğu.svg",
            Mass: 2.75,
            RadiusRatio: 0.145,
            Palette: new CharmPalette(
                new CharmColor(0.10, 0.22, 0.68),
                new CharmColor(0.06, 0.12, 0.42),
                new CharmColor(0.03, 0.06, 0.25),
                new CharmColor(0.42, 0.58, 0.95)),
            Sound: CharmSound.Glass,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "hamsa",
            DisplayName: "Hamsa",
            FileName: "Hamsa.svg",
            Mass: 3.05,
            RadiusRatio: 0.158,
            Palette: new CharmPalette(
                new CharmColor(0.15, 0.24, 0.60),
                new CharmColor(0.09, 0.14, 0.42),
                new CharmColor(0.05, 0.08, 0.26),
                new CharmColor(0.50, 0.62, 0.95)),
            Sound: CharmSound.Metal,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "nimbuMirchi",
            DisplayName: "Nimbu-mirchi",
            FileName: "Nimbu-mirchi.svg",
            Mass: 2.85,
            RadiusRatio: 0.152,
            Palette: new CharmPalette(
                new CharmColor(0.98, 0.84, 0.18),
                new CharmColor(0.85, 0.62, 0.08),
                new CharmColor(0.55, 0.38, 0.03),
                new CharmColor(1.00, 0.96, 0.62)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "ghanta",
            DisplayName: "Ghanta",
            FileName: "Ghanta.svg",
            Mass: 4.05,
            RadiusRatio: 0.15,
            Palette: new CharmPalette(
                new CharmColor(0.76, 0.45, 0.22),
                new CharmColor(0.55, 0.30, 0.13),
                new CharmColor(0.32, 0.17, 0.07),
                new CharmColor(0.98, 0.78, 0.55)),
            Sound: CharmSound.Bell,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "drishtiBommai",
            DisplayName: "Drishti bommai",
            FileName: "Dhrishti bomma.svg",
            Mass: 3.25,
            RadiusRatio: 0.164,
            Palette: new CharmPalette(
                new CharmColor(0.86, 0.14, 0.12),
                new CharmColor(0.62, 0.08, 0.08),
                new CharmColor(0.36, 0.04, 0.05),
                new CharmColor(1.00, 0.55, 0.45)),
            Sound: CharmSound.Wood,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "panchangJie",
            DisplayName: "Pánchángjié",
            FileName: "Pánchang Jié.svg",
            Mass: 2.45,
            RadiusRatio: 0.16,
            Palette: new CharmPalette(
                new CharmColor(0.88, 0.14, 0.18),
                new CharmColor(0.62, 0.08, 0.10),
                new CharmColor(0.36, 0.04, 0.06),
                new CharmColor(1.00, 0.62, 0.60)),
            Sound: CharmSound.Soft,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "daruma",
            DisplayName: "Daruma",
            FileName: "Daruma.svg",
            Mass: 3.65,
            RadiusRatio: 0.154,
            Palette: new CharmPalette(
                new CharmColor(0.88, 0.12, 0.12),
                new CharmColor(0.62, 0.06, 0.06),
                new CharmColor(0.38, 0.03, 0.03),
                new CharmColor(1.00, 0.50, 0.40)),
            Sound: CharmSound.Wood,
            BeadCount: 3,
            BodyRun: 3),
        new(
            Id: "manekiNeko",
            DisplayName: "Maneki-neko",
            FileName: "Maneki-neko.svg",
            Mass: 3.45,
            RadiusRatio: 0.167,
            Palette: new CharmPalette(
                new CharmColor(0.97, 0.95, 0.90),
                new CharmColor(0.82, 0.78, 0.70),
                new CharmColor(0.55, 0.50, 0.42),
                new CharmColor(1.00, 1.00, 1.00)),
            Sound: CharmSound.Wood,
            BeadCount: 4,
            BodyRun: 4),
        new(
            Id: "horseshoe",
            DisplayName: "Horseshoe",
            FileName: "Horseshoe.svg",
            Mass: 3.85,
            RadiusRatio: 0.151,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.60, 0.64),
                new CharmColor(0.38, 0.40, 0.44),
                new CharmColor(0.20, 0.21, 0.24),
                new CharmColor(0.88, 0.90, 0.93)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "scarab",
            DisplayName: "Scarab",
            FileName: "Scarab.svg",
            Mass: 3.15,
            RadiusRatio: 0.146,
            Palette: new CharmPalette(
                new CharmColor(0.20, 0.74, 0.76),
                new CharmColor(0.10, 0.50, 0.55),
                new CharmColor(0.05, 0.30, 0.34),
                new CharmColor(0.70, 0.95, 0.94)),
            Sound: CharmSound.Glass,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "himmeli",
            DisplayName: "Himmeli",
            FileName: "Himmeli.svg",
            Mass: 2.35,
            RadiusRatio: 0.169,
            Palette: new CharmPalette(
                new CharmColor(0.82, 0.64, 0.26),
                new CharmColor(0.60, 0.44, 0.14),
                new CharmColor(0.36, 0.26, 0.07),
                new CharmColor(0.99, 0.90, 0.60)),
            Sound: CharmSound.Soft,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "dreamCatcher",
            DisplayName: "Dream Catcher",
            FileName: "Dream Catcher.svg",
            Mass: 2.52,
            RadiusRatio: 0.1686,
            Palette: new CharmPalette(
                new CharmColor(0.62, 0.49, 0.32),
                new CharmColor(0.38, 0.30, 0.20),
                new CharmColor(0.07, 0.03, 0.01),
                new CharmColor(0.84, 0.75, 0.63)),
            Sound: CharmSound.Wood,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "snowflake",
            DisplayName: "Snowflake",
            FileName: "Snowflake.svg",
            Mass: 2.30,
            RadiusRatio: 0.1475,
            Palette: new CharmPalette(
                new CharmColor(0.42, 0.70, 0.86),
                new CharmColor(0.24, 0.47, 0.63),
                new CharmColor(0.06, 0.27, 0.41),
                new CharmColor(0.85, 0.95, 1.00)),
            Sound: CharmSound.Glass,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "bell",
            DisplayName: "Bell",
            FileName: "Bell.svg",
            Mass: 3.10,
            RadiusRatio: 0.1530,
            Palette: new CharmPalette(
                new CharmColor(0.84, 0.60, 0.17),
                new CharmColor(0.60, 0.40, 0.08),
                new CharmColor(0.29, 0.17, 0.02),
                new CharmColor(1.00, 0.90, 0.65)),
            Sound: CharmSound.Bell,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "candyCane",
            DisplayName: "Candy Cane",
            FileName: "Candy Cane.svg",
            Mass: 2.42,
            RadiusRatio: 0.1435,
            Palette: new CharmPalette(
                new CharmColor(0.88, 0.16, 0.11),
                new CharmColor(0.63, 0.08, 0.05),
                new CharmColor(0.37, 0.04, 0.03),
                new CharmColor(1.00, 0.85, 0.82)),
            Sound: CharmSound.Wood,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "pumpkin",
            DisplayName: "Pumpkin",
            FileName: "Pumpkin.svg",
            Mass: 3.35,
            RadiusRatio: 0.1615,
            Palette: new CharmPalette(
                new CharmColor(0.94, 0.48, 0.09),
                new CharmColor(0.68, 0.29, 0.03),
                new CharmColor(0.36, 0.14, 0.02),
                new CharmColor(1.00, 0.77, 0.42)),
            Sound: CharmSound.Wood,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "ghost",
            DisplayName: "Ghost",
            FileName: "Ghost.svg",
            Mass: 2.15,
            RadiusRatio: 0.1555,
            Palette: new CharmPalette(
                new CharmColor(0.87, 0.89, 0.96),
                new CharmColor(0.56, 0.60, 0.77),
                new CharmColor(0.23, 0.27, 0.41),
                new CharmColor(1.00, 1.00, 1.00)),
            Sound: CharmSound.Soft,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "bat",
            DisplayName: "Bat",
            FileName: "Bat.svg",
            Mass: 2.55,
            RadiusRatio: 0.1595,
            Palette: new CharmPalette(
                new CharmColor(0.42, 0.28, 0.62),
                new CharmColor(0.23, 0.14, 0.38),
                new CharmColor(0.09, 0.05, 0.16),
                new CharmColor(0.72, 0.60, 0.90)),
            Sound: CharmSound.Soft,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "diya",
            DisplayName: "Diya",
            FileName: "Diya.svg",
            Mass: 3.00,
            RadiusRatio: 0.1545,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.34, 0.11),
                new CharmColor(0.47, 0.20, 0.05),
                new CharmColor(0.23, 0.09, 0.02),
                new CharmColor(1.00, 0.81, 0.42)),
            Sound: CharmSound.Wood,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "lotus",
            DisplayName: "Lotus",
            FileName: "Lotus.svg",
            Mass: 2.50,
            RadiusRatio: 0.1585,
            Palette: new CharmPalette(
                new CharmColor(0.94, 0.42, 0.65),
                new CharmColor(0.64, 0.19, 0.42),
                new CharmColor(0.33, 0.06, 0.20),
                new CharmColor(1.00, 0.84, 0.92)),
            Sound: CharmSound.Soft,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "lantern",
            DisplayName: "Lantern",
            FileName: "Lantern.svg",
            Mass: 2.95,
            RadiusRatio: 0.1505,
            Palette: new CharmPalette(
                new CharmColor(0.85, 0.13, 0.11),
                new CharmColor(0.58, 0.07, 0.05),
                new CharmColor(0.30, 0.03, 0.02),
                new CharmColor(1.00, 0.70, 0.55)),
            Sound: CharmSound.Wood,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "firework",
            DisplayName: "Firework",
            FileName: "Firework.svg",
            Mass: 2.40,
            RadiusRatio: 0.1565,
            Palette: new CharmPalette(
                new CharmColor(0.95, 0.70, 0.18),
                new CharmColor(0.66, 0.42, 0.05),
                new CharmColor(0.20, 0.09, 0.32),
                new CharmColor(1.00, 0.94, 0.74)),
            Sound: CharmSound.Glass,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "luckyCoin",
            DisplayName: "Lucky Coin",
            FileName: "Lucky Coin.svg",
            Mass: 3.20,
            RadiusRatio: 0.1465,
            Palette: new CharmPalette(
                new CharmColor(0.82, 0.63, 0.20),
                new CharmColor(0.55, 0.39, 0.06),
                new CharmColor(0.28, 0.19, 0.02),
                new CharmColor(1.00, 0.93, 0.72)),
            Sound: CharmSound.Metal,
            BeadCount: 2,
            BodyRun: 2),
        new(
            Id: "spiderMan",
            DisplayName: "Spider-Man",
            FileName: "Avengers/Spider-Man.svg",
            Mass: 2.96,
            RadiusRatio: 0.1525,
            Palette: new CharmPalette(
                new CharmColor(0.53, 0.17, 0.26),
                new CharmColor(0.33, 0.11, 0.16),
                new CharmColor(0.05, 0.04, 0.11),
                new CharmColor(0.61, 0.50, 0.58)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "captainAmericaShield",
            DisplayName: "Captain America Shield",
            FileName: "Avengers/Captain-America.svg",
            Mass: 3.46,
            RadiusRatio: 0.1515,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.13, 0.17),
                new CharmColor(0.43, 0.08, 0.11),
                new CharmColor(0.09, 0.04, 0.09),
                new CharmColor(0.73, 0.74, 0.74)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "ironManHelmet",
            DisplayName: "Iron Man Helmet",
            FileName: "Avengers/Iron-Man.svg",
            Mass: 3.26,
            RadiusRatio: 0.1495,
            Palette: new CharmPalette(
                new CharmColor(0.69, 0.34, 0.29),
                new CharmColor(0.43, 0.21, 0.18),
                new CharmColor(0.16, 0.03, 0.04),
                new CharmColor(0.98, 0.92, 0.87)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "thorHammer",
            DisplayName: "Thor Hammer",
            FileName: "Avengers/Thor Mjölnir.svg",
            Mass: 3.91,
            RadiusRatio: 0.1535,
            Palette: new CharmPalette(
                new CharmColor(0.43, 0.51, 0.56),
                new CharmColor(0.26, 0.32, 0.34),
                new CharmColor(0.11, 0.12, 0.14),
                new CharmColor(0.85, 0.88, 0.88)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "hulkFist",
            DisplayName: "Hulk Fist",
            FileName: "Avengers/Hulk.svg",
            Mass: 3.71,
            RadiusRatio: 0.1550,
            Palette: new CharmPalette(
                new CharmColor(0.19, 0.54, 0.24),
                new CharmColor(0.12, 0.34, 0.15),
                new CharmColor(0.06, 0.09, 0.06),
                new CharmColor(0.39, 0.63, 0.42)),
            Sound: CharmSound.Wood,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "spiderManSwinging",
            DisplayName: "Spider-Man Swinging",
            FileName: "Avengers/Spider-Man Swinging.svg",
            Mass: 3.01,
            RadiusRatio: 0.1528,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.26, 0.33),
                new CharmColor(0.36, 0.16, 0.20),
                new CharmColor(0.07, 0.04, 0.08),
                new CharmColor(0.67, 0.54, 0.56)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "batmanSymbol",
            DisplayName: "Batman Symbol",
            FileName: "DC/Bat-Man.svg",
            Mass: 3.31,
            RadiusRatio: 0.1575,
            Palette: new CharmPalette(
                new CharmColor(0.33, 0.38, 0.47),
                new CharmColor(0.20, 0.23, 0.29),
                new CharmColor(0.04, 0.05, 0.06),
                new CharmColor(0.64, 0.61, 0.59)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "supermanShield",
            DisplayName: "Superman Shield",
            FileName: "DC/Super-Man.svg",
            Mass: 3.36,
            RadiusRatio: 0.1590,
            Palette: new CharmPalette(
                new CharmColor(0.48, 0.21, 0.15),
                new CharmColor(0.30, 0.13, 0.10),
                new CharmColor(0.17, 0.01, 0.01),
                new CharmColor(0.85, 0.81, 0.76)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "wonderWomanEmblem",
            DisplayName: "Wonder Woman Emblem",
            FileName: "DC/Wonder Women.svg",
            Mass: 3.21,
            RadiusRatio: 0.1605,
            Palette: new CharmPalette(
                new CharmColor(0.72, 0.54, 0.38),
                new CharmColor(0.45, 0.34, 0.23),
                new CharmColor(0.06, 0.02, 0.03),
                new CharmColor(0.92, 0.83, 0.66)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "shazamLightning",
            DisplayName: "Shazam Lightning",
            FileName: "DC/Flash.svg",
            Mass: 2.91,
            RadiusRatio: 0.1485,
            Palette: new CharmPalette(
                new CharmColor(0.57, 0.15, 0.10),
                new CharmColor(0.35, 0.09, 0.06),
                new CharmColor(0.31, 0.03, 0.03),
                new CharmColor(0.94, 0.87, 0.70)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "greenLanternRing",
            DisplayName: "Green Lantern Ring",
            FileName: "DC/Green Lantern.svg",
            Mass: 3.06,
            RadiusRatio: 0.1610,
            Palette: new CharmPalette(
                new CharmColor(0.07, 0.73, 0.40),
                new CharmColor(0.04, 0.45, 0.25),
                new CharmColor(0.08, 0.20, 0.16),
                new CharmColor(0.86, 0.92, 0.88)),
            Sound: CharmSound.Glass,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "vel",
            DisplayName: "Vel",
            FileName: "Tamil Gods/Muruga Vel.svg",
            Mass: 3.11,
            RadiusRatio: 0.1620,
            Palette: new CharmPalette(
                new CharmColor(0.72, 0.56, 0.33),
                new CharmColor(0.44, 0.35, 0.21),
                new CharmColor(0.28, 0.16, 0.10),
                new CharmColor(0.86, 0.76, 0.54)),
            Sound: CharmSound.Metal,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "vinayagarCoin",
            DisplayName: "Vinayagar Coin",
            FileName: "Tamil Gods/Vinayaga.svg",
            Mass: 3.16,
            RadiusRatio: 0.1468,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.54, 0.29),
                new CharmColor(0.44, 0.34, 0.18),
                new CharmColor(0.24, 0.13, 0.06),
                new CharmColor(0.79, 0.65, 0.40)),
            Sound: CharmSound.Metal,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "omSymbol",
            DisplayName: "OM Symbol",
            FileName: "Tamil Gods/OM.svg",
            Mass: 2.97,
            RadiusRatio: 0.1630,
            Palette: new CharmPalette(
                new CharmColor(0.67, 0.43, 0.33),
                new CharmColor(0.42, 0.27, 0.20),
                new CharmColor(0.33, 0.15, 0.13),
                new CharmColor(0.98, 0.92, 0.74)),
            Sound: CharmSound.Metal,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "karuppuStatue",
            DisplayName: "Karuppu Statue",
            FileName: "Tamil Gods/Karuppu.svg",
            Mass: 3.61,
            RadiusRatio: 0.1635,
            Palette: new CharmPalette(
                new CharmColor(0.51, 0.38, 0.30),
                new CharmColor(0.32, 0.24, 0.18),
                new CharmColor(0.06, 0.05, 0.04),
                new CharmColor(0.59, 0.49, 0.43)),
            Sound: CharmSound.Wood,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "templeBell",
            DisplayName: "Temple Bell",
            FileName: "Tamil Gods/Mani.svg",
            Mass: 3.41,
            RadiusRatio: 0.1645,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.47, 0.32),
                new CharmColor(0.39, 0.29, 0.20),
                new CharmColor(0.24, 0.15, 0.10),
                new CharmColor(0.78, 0.66, 0.53)),
            Sound: CharmSound.Bell,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "btsMemberOne",
            DisplayName: "RM",
            FileName: "BTS/RM.svg",
            Mass: 2.65,
            RadiusRatio: 0.1593,
            Palette: new CharmPalette(
                new CharmColor(0.53, 0.34, 0.63),
                new CharmColor(0.33, 0.21, 0.39),
                new CharmColor(0.11, 0.07, 0.14),
                new CharmColor(0.85, 0.79, 0.79)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberTwo",
            DisplayName: "Jin",
            FileName: "BTS/Jin.svg",
            Mass: 2.68,
            RadiusRatio: 0.1601,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.50, 0.41),
                new CharmColor(0.41, 0.31, 0.25),
                new CharmColor(0.04, 0.03, 0.04),
                new CharmColor(0.86, 0.73, 0.65)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberThree",
            DisplayName: "SUGA",
            FileName: "BTS/SUGA.svg",
            Mass: 2.71,
            RadiusRatio: 0.1609,
            Palette: new CharmPalette(
                new CharmColor(0.73, 0.55, 0.53),
                new CharmColor(0.45, 0.34, 0.33),
                new CharmColor(0.55, 0.40, 0.46),
                new CharmColor(0.89, 0.83, 0.83)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberFour",
            DisplayName: "j-hope",
            FileName: "BTS/j-hope.svg",
            Mass: 2.74,
            RadiusRatio: 0.1617,
            Palette: new CharmPalette(
                new CharmColor(0.44, 0.39, 0.48),
                new CharmColor(0.27, 0.24, 0.30),
                new CharmColor(0.10, 0.08, 0.11),
                new CharmColor(0.86, 0.84, 0.86)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberFive",
            DisplayName: "Jimin",
            FileName: "BTS/Jimin.svg",
            Mass: 2.77,
            RadiusRatio: 0.1625,
            Palette: new CharmPalette(
                new CharmColor(0.52, 0.29, 0.67),
                new CharmColor(0.32, 0.18, 0.41),
                new CharmColor(0.12, 0.07, 0.18),
                new CharmColor(0.79, 0.62, 0.78)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberSix",
            DisplayName: "V",
            FileName: "BTS/V.svg",
            Mass: 2.80,
            RadiusRatio: 0.1633,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.46, 0.33),
                new CharmColor(0.43, 0.29, 0.21),
                new CharmColor(0.53, 0.32, 0.23),
                new CharmColor(0.94, 0.85, 0.78)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "btsMemberSeven",
            DisplayName: "Jungkook",
            FileName: "BTS/Jungkook.svg",
            Mass: 2.83,
            RadiusRatio: 0.1641,
            Palette: new CharmPalette(
                new CharmColor(0.55, 0.35, 0.67),
                new CharmColor(0.34, 0.22, 0.42),
                new CharmColor(0.03, 0.02, 0.05),
                new CharmColor(0.87, 0.74, 0.83)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "ronaldoJersey",
            DisplayName: "Ronaldo 7",
            FileName: "Football/Ronaldo 7.svg",
            Mass: 3.02,
            RadiusRatio: 0.1652,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.06, 0.09),
                new CharmColor(0.36, 0.03, 0.06),
                new CharmColor(0.42, 0.01, 0.03),
                new CharmColor(0.93, 0.83, 0.64)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "messiJersey",
            DisplayName: "Messi 10",
            FileName: "Football/Messi 10.svg",
            Mass: 3.08,
            RadiusRatio: 0.1656,
            Palette: new CharmPalette(
                new CharmColor(0.35, 0.58, 0.72),
                new CharmColor(0.22, 0.36, 0.44),
                new CharmColor(0.11, 0.14, 0.22),
                new CharmColor(0.90, 0.90, 0.90)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "neymarJersey",
            DisplayName: "Neymar 10",
            FileName: "Football/Neymar 10.svg",
            Mass: 3.13,
            RadiusRatio: 0.1660,
            Palette: new CharmPalette(
                new CharmColor(0.87, 0.71, 0.02),
                new CharmColor(0.54, 0.44, 0.01),
                new CharmColor(0.14, 0.38, 0.15),
                new CharmColor(0.93, 0.83, 0.40)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "realMadridCrest",
            DisplayName: "Real Madrid",
            FileName: "Football/Real Madrid.svg",
            Mass: 3.18,
            RadiusRatio: 0.1664,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.53, 0.31),
                new CharmColor(0.44, 0.33, 0.19),
                new CharmColor(0.11, 0.09, 0.32),
                new CharmColor(0.92, 0.91, 0.89)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "fcBarcelonaCrest",
            DisplayName: "FC Barcelona",
            FileName: "Football/FC Barcelona.svg",
            Mass: 3.23,
            RadiusRatio: 0.1668,
            Palette: new CharmPalette(
                new CharmColor(0.46, 0.15, 0.29),
                new CharmColor(0.28, 0.09, 0.18),
                new CharmColor(0.30, 0.04, 0.19),
                new CharmColor(0.91, 0.86, 0.76)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "billieEilish",
            DisplayName: "Billie Eilish",
            FileName: "Music/Billie Eilish.svg",
            Mass: 2.62,
            RadiusRatio: 0.1672,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.62, 0.37),
                new CharmColor(0.40, 0.38, 0.23),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.73, 0.71, 0.49)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "xxxtentacion",
            DisplayName: "XXXTentacion",
            FileName: "Music/XXXTentacion.svg",
            Mass: 2.67,
            RadiusRatio: 0.1676,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.49, 0.34),
                new CharmColor(0.41, 0.30, 0.21),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.73, 0.57, 0.42)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "michaelJackson",
            DisplayName: "Michael Jackson",
            FileName: "Music/Michael Jackson.svg",
            Mass: 2.72,
            RadiusRatio: 0.1680,
            Palette: new CharmPalette(
                new CharmColor(0.55, 0.30, 0.24),
                new CharmColor(0.34, 0.18, 0.15),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.76, 0.72, 0.68)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "taylorSwift",
            DisplayName: "Taylor Swift",
            FileName: "Music/Taylor Swift.svg",
            Mass: 2.78,
            RadiusRatio: 0.1684,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.52, 0.39),
                new CharmColor(0.44, 0.32, 0.24),
                new CharmColor(0.06, 0.04, 0.03),
                new CharmColor(0.82, 0.73, 0.67)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "juiceWrld",
            DisplayName: "Juice WRLD",
            FileName: "Music/Juice WRLD.svg",
            Mass: 2.84,
            RadiusRatio: 0.1688,
            Palette: new CharmPalette(
                new CharmColor(0.51, 0.34, 0.24),
                new CharmColor(0.32, 0.21, 0.15),
                new CharmColor(0.01, 0.00, 0.00),
                new CharmColor(0.68, 0.64, 0.60)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "theWeeknd",
            DisplayName: "The Weeknd",
            FileName: "Music/The Weeknd.svg",
            Mass: 2.89,
            RadiusRatio: 0.1694,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.26, 0.24),
                new CharmColor(0.38, 0.16, 0.15),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.64, 0.40, 0.31)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "rachelGreen",
            DisplayName: "Rachel Green",
            FileName: "Friends/Rachel Green.svg",
            Mass: 2.87,
            RadiusRatio: 0.1692,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.44, 0.32),
                new CharmColor(0.40, 0.28, 0.20),
                new CharmColor(0.06, 0.04, 0.03),
                new CharmColor(0.73, 0.60, 0.52)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "monicaGeller",
            DisplayName: "Monica Geller",
            FileName: "Friends/Monica Geller.svg",
            Mass: 2.92,
            RadiusRatio: 0.1696,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.47, 0.37),
                new CharmColor(0.41, 0.29, 0.23),
                new CharmColor(0.01, 0.01, 0.00),
                new CharmColor(0.69, 0.51, 0.41)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "rossGeller",
            DisplayName: "Ross Geller",
            FileName: "Friends/Ross Geller.svg",
            Mass: 2.98,
            RadiusRatio: 0.1702,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.46, 0.35),
                new CharmColor(0.41, 0.29, 0.21),
                new CharmColor(0.03, 0.02, 0.01),
                new CharmColor(0.71, 0.54, 0.43)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "joeyTribbiani",
            DisplayName: "Joey Tribbiani",
            FileName: "Friends/Joey Tribbiani.svg",
            Mass: 3.03,
            RadiusRatio: 0.1706,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.44, 0.33),
                new CharmColor(0.40, 0.27, 0.20),
                new CharmColor(0.04, 0.03, 0.02),
                new CharmColor(0.74, 0.64, 0.58)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "chandlerBing",
            DisplayName: "Chandler Bing",
            FileName: "Friends/Chandler Bing.svg",
            Mass: 3.09,
            RadiusRatio: 0.1710,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.43, 0.34),
                new CharmColor(0.38, 0.27, 0.21),
                new CharmColor(0.04, 0.03, 0.02),
                new CharmColor(0.69, 0.54, 0.47)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "phoebeBuffay",
            DisplayName: "Phoebe Buffay",
            FileName: "Friends/Phoebe Buffay.svg",
            Mass: 3.14,
            RadiusRatio: 0.1714,
            Palette: new CharmPalette(
                new CharmColor(0.68, 0.45, 0.26),
                new CharmColor(0.42, 0.28, 0.16),
                new CharmColor(0.08, 0.04, 0.02),
                new CharmColor(0.77, 0.60, 0.48)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "walterWhite",
            DisplayName: "Walter White",
            FileName: "Breaking Bad/Walter White.svg",
            Mass: 3.28,
            RadiusRatio: 0.1718,
            Palette: new CharmPalette(
                new CharmColor(0.78, 0.56, 0.14),
                new CharmColor(0.48, 0.35, 0.09),
                new CharmColor(0.07, 0.05, 0.04),
                new CharmColor(0.89, 0.73, 0.47)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "jessePinkman",
            DisplayName: "Jesse Pinkman",
            FileName: "Breaking Bad/Jesse Pinkman.svg",
            Mass: 3.33,
            RadiusRatio: 0.1722,
            Palette: new CharmPalette(
                new CharmColor(0.74, 0.51, 0.11),
                new CharmColor(0.46, 0.32, 0.07),
                new CharmColor(0.02, 0.02, 0.01),
                new CharmColor(0.80, 0.62, 0.35)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "saulGoodman",
            DisplayName: "Saul Goodman",
            FileName: "Breaking Bad/Saul Goodman.svg",
            Mass: 3.38,
            RadiusRatio: 0.1726,
            Palette: new CharmPalette(
                new CharmColor(0.76, 0.57, 0.34),
                new CharmColor(0.47, 0.35, 0.21),
                new CharmColor(0.03, 0.02, 0.02),
                new CharmColor(0.81, 0.62, 0.41)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "gusFring",
            DisplayName: "Gus Fring",
            FileName: "Breaking Bad/Gus Fring.svg",
            Mass: 3.43,
            RadiusRatio: 0.1730,
            Palette: new CharmPalette(
                new CharmColor(0.54, 0.33, 0.21),
                new CharmColor(0.33, 0.21, 0.13),
                new CharmColor(0.01, 0.02, 0.02),
                new CharmColor(0.60, 0.47, 0.40)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "mikeEhrmantraut",
            DisplayName: "Mike Ehrmantraut",
            FileName: "Breaking Bad/Mike Ehrmantraut.svg",
            Mass: 3.48,
            RadiusRatio: 0.1734,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.47, 0.36),
                new CharmColor(0.43, 0.29, 0.22),
                new CharmColor(0.01, 0.01, 0.01),
                new CharmColor(0.76, 0.55, 0.44)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "heisenberg",
            DisplayName: "Heisenberg",
            FileName: "Breaking Bad/Heisenberg.svg",
            Mass: 3.53,
            RadiusRatio: 0.1738,
            Palette: new CharmPalette(
                new CharmColor(0.47, 0.39, 0.32),
                new CharmColor(0.29, 0.24, 0.20),
                new CharmColor(0.01, 0.01, 0.01),
                new CharmColor(0.55, 0.47, 0.41)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "rv",
            DisplayName: "RV",
            FileName: "Breaking Bad/RV.svg",
            Mass: 3.58,
            RadiusRatio: 0.1766,
            Palette: new CharmPalette(
                new CharmColor(0.81, 0.64, 0.40),
                new CharmColor(0.50, 0.40, 0.25),
                new CharmColor(0.03, 0.02, 0.01),
                new CharmColor(0.94, 0.82, 0.66)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "eleven",
            DisplayName: "Eleven",
            FileName: "Stranger Things/Eleven.svg",
            Mass: 2.24,
            RadiusRatio: 0.1742,
            Palette: new CharmPalette(
                new CharmColor(0.69, 0.45, 0.34),
                new CharmColor(0.43, 0.28, 0.21),
                new CharmColor(0.07, 0.07, 0.08),
                new CharmColor(0.78, 0.65, 0.61)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "mikeWheeler",
            DisplayName: "Mike Wheeler",
            FileName: "Stranger Things/Mike Wheeler.svg",
            Mass: 2.28,
            RadiusRatio: 0.1746,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.42, 0.32),
                new CharmColor(0.38, 0.26, 0.20),
                new CharmColor(0.02, 0.02, 0.01),
                new CharmColor(0.71, 0.57, 0.49)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "dustinHenderson",
            DisplayName: "Dustin Henderson",
            FileName: "Stranger Things/Dustin Henderson.svg",
            Mass: 2.33,
            RadiusRatio: 0.1750,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.43, 0.31),
                new CharmColor(0.40, 0.27, 0.19),
                new CharmColor(0.04, 0.02, 0.01),
                new CharmColor(0.80, 0.69, 0.64)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "lucasSinclair",
            DisplayName: "Lucas Sinclair",
            FileName: "Stranger Things/Lucas Sinclair.svg",
            Mass: 2.38,
            RadiusRatio: 0.1754,
            Palette: new CharmPalette(
                new CharmColor(0.48, 0.26, 0.15),
                new CharmColor(0.30, 0.16, 0.09),
                new CharmColor(0.04, 0.02, 0.01),
                new CharmColor(0.66, 0.54, 0.45)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "willByers",
            DisplayName: "Will Byers",
            FileName: "Stranger Things/Will Byers.svg",
            Mass: 2.44,
            RadiusRatio: 0.1758,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.42, 0.23),
                new CharmColor(0.40, 0.26, 0.15),
                new CharmColor(0.06, 0.03, 0.01),
                new CharmColor(0.77, 0.61, 0.43)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "demogorgon",
            DisplayName: "Demogorgon",
            FileName: "Stranger Things/Demogorgon.svg",
            Mass: 2.48,
            RadiusRatio: 0.1762,
            Palette: new CharmPalette(
                new CharmColor(0.57, 0.24, 0.19),
                new CharmColor(0.36, 0.15, 0.12),
                new CharmColor(0.09, 0.02, 0.01),
                new CharmColor(0.67, 0.52, 0.47)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "circle",
            DisplayName: "Bead",
            FileName: "Bead.svg",
            Mass: 2.6,
            RadiusRatio: 0.140,
            Palette: new CharmPalette(
                new CharmColor(0.12, 0.20, 0.66),
                new CharmColor(0.07, 0.12, 0.44),
                new CharmColor(0.03, 0.06, 0.24),
                new CharmColor(0.46, 0.58, 0.95)),
            Sound: CharmSound.Glass,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "camera",
            DisplayName: "Camera",
            FileName: "Camera.svg",
            Mass: 4.2,
            RadiusRatio: 0.170,
            Palette: new CharmPalette(
                new CharmColor(0.36, 0.38, 0.43),
                new CharmColor(0.20, 0.22, 0.26),
                new CharmColor(0.09, 0.10, 0.12),
                new CharmColor(0.74, 0.77, 0.82)),
            Sound: CharmSound.Metal,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "star",
            DisplayName: "Star",
            FileName: "Star.svg",
            Mass: 2.2,
            RadiusRatio: 0.157,
            Palette: new CharmPalette(
                new CharmColor(1.00, 0.78, 0.25),
                new CharmColor(0.93, 0.58, 0.10),
                new CharmColor(0.62, 0.35, 0.03),
                new CharmColor(1.00, 0.93, 0.70)),
            Sound: CharmSound.Soft,
            BeadCount: 1,
            BodyRun: 1),
        new(
            Id: "heart",
            DisplayName: "Heart",
            FileName: "Heart.svg",
            Mass: 2.9,
            RadiusRatio: 0.149,
            Palette: new CharmPalette(
                new CharmColor(0.93, 0.70, 0.74),
                new CharmColor(0.82, 0.51, 0.57),
                new CharmColor(0.54, 0.29, 0.34),
                new CharmColor(1.00, 0.90, 0.92)),
            Sound: CharmSound.Soft,
            BeadCount: 0,
            BodyRun: 0),
        new(
            Id: "diamond",
            DisplayName: "Diamond",
            FileName: "Diamond.svg",
            Mass: 3.4,
            RadiusRatio: 0.142,
            Palette: new CharmPalette(
                new CharmColor(0.62, 0.88, 0.97),
                new CharmColor(0.35, 0.68, 0.88),
                new CharmColor(0.18, 0.42, 0.62),
                new CharmColor(0.90, 0.98, 1.00)),
            Sound: CharmSound.Glass,
            BeadCount: 0,
            BodyRun: 0),
    ];
}
